In [73]:
import numpy as np
from scipy import stats
import mathfunctions as mathf

In [74]:
data = np.random.rand(8, 4)
print(data)

[[0.82854209 0.56266984 0.85626931 0.96654325]
 [0.39735142 0.99469414 0.95453391 0.12736522]
 [0.95251538 0.19565402 0.59452926 0.88240193]
 [0.38640384 0.58271618 0.50508356 0.57361778]
 [0.15223872 0.92398026 0.91894997 0.16207546]
 [0.87709014 0.72292051 0.76818582 0.57866036]
 [0.65085683 0.70042638 0.68146256 0.42859766]
 [0.25274953 0.10596337 0.10388612 0.14825328]]


In [75]:
data = data.T
print(data)

[[0.82854209 0.39735142 0.95251538 0.38640384 0.15223872 0.87709014
  0.65085683 0.25274953]
 [0.56266984 0.99469414 0.19565402 0.58271618 0.92398026 0.72292051
  0.70042638 0.10596337]
 [0.85626931 0.95453391 0.59452926 0.50508356 0.91894997 0.76818582
  0.68146256 0.10388612]
 [0.96654325 0.12736522 0.88240193 0.57361778 0.16207546 0.57866036
  0.42859766 0.14825328]]


In [76]:
coli = [i for i in range(len(data)) if i % 2 == 0]
colq = [i for i in range(len(data)) if i % 2 != 0]
idata1 = data[coli, :]
qdata1 = data[colq, :]
print('idata1 = \n', idata1, '\nqdata1 = \n', qdata1)

idata1 = 
 [[0.82854209 0.39735142 0.95251538 0.38640384 0.15223872 0.87709014
  0.65085683 0.25274953]
 [0.85626931 0.95453391 0.59452926 0.50508356 0.91894997 0.76818582
  0.68146256 0.10388612]] 
qdata1 = 
 [[0.56266984 0.99469414 0.19565402 0.58271618 0.92398026 0.72292051
  0.70042638 0.10596337]
 [0.96654325 0.12736522 0.88240193 0.57361778 0.16207546 0.57866036
  0.42859766 0.14825328]]


In [77]:
signali = np.ravel(idata1.T)
signalq = np.ravel(qdata1.T)
print('signali = \n', signali, '\nsignalq = \n', signalq)

signali = 
 [0.82854209 0.85626931 0.39735142 0.95453391 0.95251538 0.59452926
 0.38640384 0.50508356 0.15223872 0.91894997 0.87709014 0.76818582
 0.65085683 0.68146256 0.25274953 0.10388612] 
signalq = 
 [0.56266984 0.96654325 0.99469414 0.12736522 0.19565402 0.88240193
 0.58271618 0.57361778 0.92398026 0.16207546 0.72292051 0.57866036
 0.70042638 0.42859766 0.10596337 0.14825328]


In [78]:
avg = stats.trim_mean(idata1, 0)
print('avg = ', avg, '\nidata1 = ', idata1,'\nidata1 - avg = ', idata1 - avg)

avg =  [0.8424057  0.67594267 0.77352232 0.4457437  0.53559434 0.82263798
 0.66615969 0.17831782] 
idata1 =  [[0.82854209 0.39735142 0.95251538 0.38640384 0.15223872 0.87709014
  0.65085683 0.25274953]
 [0.85626931 0.95453391 0.59452926 0.50508356 0.91894997 0.76818582
  0.68146256 0.10388612]] 
idata1 - avg =  [[-0.01386361 -0.27859124  0.17899306 -0.05933986 -0.38335563  0.05445216
  -0.01530287  0.0744317 ]
 [ 0.01386361  0.27859124 -0.17899306  0.05933986  0.38335563 -0.05445216
   0.01530287 -0.0744317 ]]


In [81]:
diff = np.abs(idata1 - avg)
[max, pos] = mathf.MaxColumnWise(diff)
print(max, pos)

[0.01386361 0.27859124 0.17899306 0.05933986 0.38335563 0.05445216
 0.01530287 0.0744317 ] [0 0 0 0 0 0 0 0]


In [83]:
matrix = [[1, 4, 9], [7, 2, 0], [6, 100, 0]]
[max, pos] = mathf.MaxColumnWise(matrix)
print (max, pos)

[  7 100   9] [1 2 0]


In [85]:
if pos[0]/1 > 0:
    print('sus')

sus
